create extension if not exists pgcrypto;

create table public.games (
  id uuid primary key default gen_random_uuid(),
  room_code text not null unique check (room_code ~ '^[A-Z0-9]{4,8}$'),
  host_id uuid not null references auth.users(id) on delete cascade,
  topic text not null check (char_length(topic) between 1 and 80),
  mode text not null check (mode in ('topic', 'numbers')),
  board_size integer not null check (board_size between 3 and 6),
  word_pool jsonb not null check (jsonb_typeof(word_pool) = 'array'),
  free_center boolean not null default false,
  status text not null default 'waiting' check (status in ('waiting', 'playing', 'finished')),
  created_at timestamptz not null default now(),
  started_at timestamptz,
  ended_at timestamptz
);

create table public.game_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 20),
  board jsonb not null check (jsonb_typeof(board) = 'array'),
  marked_cells jsonb not null default '[]'::jsonb check (jsonb_typeof(marked_cells) = 'array'),
  bingo_count integer not null default 0 check (bingo_count >= 0),
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, user_id)
);

create table public.game_events (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 20),
  event_type text not null check (event_type in ('joined', 'started', 'marked', 'unmarked', 'bingo', 'finished')),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);

create index games_room_code_idx on public.games (room_code);
create index game_players_game_id_idx on public.game_players (game_id, joined_at);
create index game_events_game_id_idx on public.game_events (game_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_game_member(target_game_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.game_players
    where game_players.game_id = target_game_id
      and game_players.user_id = auth.uid()
  );
$$;

create trigger game_players_set_updated_at
before update on public.game_players
for each row execute function public.set_updated_at();

alter table public.games enable row level security;
alter table public.game_players enable row level security;
alter table public.game_events enable row level security;

create policy "signed in players can find games"
on public.games for select
to authenticated
using (true);

create policy "users can create hosted games"
on public.games for insert
to authenticated
with check (auth.uid() = host_id);

create policy "hosts can update their games"
on public.games for update
to authenticated
using (auth.uid() = host_id)
with check (auth.uid() = host_id);

create policy "players can view room participants"
on public.game_players for select
to authenticated
using (auth.uid() = user_id or public.is_game_member(game_id));

create policy "users can join waiting games"
on public.game_players for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1 from public.games
    where games.id = game_players.game_id
      and games.status = 'waiting'
  )
);

create policy "players can update their own board"
on public.game_players for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "players can view game events"
on public.game_events for select
to authenticated
using (public.is_game_member(game_id));

create policy "players can append their own events"
on public.game_events for insert
to authenticated
with check (
  auth.uid() = user_id
  and public.is_game_member(game_id)
);

grant usage on schema public to authenticated;
grant select, insert, update on public.games to authenticated;
grant select, insert, update on public.game_players to authenticated;
grant select, insert on public.game_events to authenticated;
grant usage, select on sequence public.game_events_id_seq to authenticated;
revoke all on function public.is_game_member(uuid) from public;
grant execute on function public.is_game_member(uuid) to authenticated;

alter table public.games replica identity full;
alter table public.game_players replica identity full;
alter table public.game_events replica identity full;

alter publication supabase_realtime add table public.games;
alter publication supabase_realtime add table public.game_players;
alter publication supabase_realtime add table public.game_events;
